# Generated by Django 6.0.4 on 2026-04-29 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_shop_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_accent',
            field=models.CharField(default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='uz', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Novice', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='dark', max_length=10),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=128)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='hp', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
