# Generated by Django 6.0 on 2026-05-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
