
"""
Django settings for mlw project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))

# Prefer `.env` (standard), but keep `env` as a legacy fallback.
# Also avoid trying to read a venv directory named `env/`.
for env_path in (BASE_DIR / ".env", BASE_DIR / "env"):
    if env_path.is_file():
        environ.Env.read_env(str(env_path))
        break

SECRET_KEY = env.str("SECRET_KEY")
DEBUG = env.bool("DEBUG", default=False)


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'movies',
    'users',
    'hitcount',
    'mlw'
]

AUTH_USER_MODEL = 'users.User'

middleware_base = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    middleware_base = [
        'django.middleware.cache.UpdateCacheMiddleware',
    ] + middleware_base + [
        'django.middleware.cache.FetchFromCacheMiddleware',
    ]

MIDDLEWARE = middleware_base

ROOT_URLCONF = 'mlw.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # custom
                'movies.context_processor.movie_context',
                'users.context_processor.user_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'mlw.wsgi.application'


# Database
# Prefer `DATABASE_URL` in production (Postgres). Falls back to SQLite for
# local development when `DATABASE_URL` is not provided.
# Example `DATABASE_URL`: postgres://USER:PASSWORD@HOST:PORT/NAME
DATABASE_URL = env.str('DATABASE_URL', default='')
if DATABASE_URL:
    DATABASES = {
        'default': env.db('DATABASE_URL')
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR / 'static'
STATIC_ROOT = str(BASE_DIR.joinpath('staticfiles'))
STATICFILES_DIR = (str(BASE_DIR.joinpath('static')),)
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Use WhiteNoise to serve compressed static files efficiently
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Toggle site-wide game availability. Set to False to disable Battle Arena for all users.
GAME_ENABLED = env.bool("GAME_ENABLED", default=False)

# Redis cache / session configuration (use REDIS_URL env, e.g. Upstash)
REDIS_URL = env.str('REDIS_URL', default=None)
REDIS_AVAILABLE = REDIS_URL is not None

if REDIS_AVAILABLE:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            # Default timeout for cache entries (seconds). Can be overridden
            # using the CACHE_TIMEOUT env var.
            'TIMEOUT': env.int('CACHE_TIMEOUT', default=86400),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'TIMEOUT': env.int('CACHE_TIMEOUT', default=86400),
        }
    }

# Cache middleware settings
CACHE_MIDDLEWARE_SECONDS = env.int('CACHE_MIDDLEWARE_SECONDS', default=300)
CACHE_MIDDLEWARE_KEY_PREFIX = env.str('CACHE_MIDDLEWARE_KEY_PREFIX', default='mlw')

if DEBUG:
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
else:
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'

SESSION_COOKIE_AGE = env.int('SESSION_COOKIE_AGE', default=1209600)
SESSION_EXPIRE_AT_BROWSER_CLOSE = env.bool('SESSION_EXPIRE_AT_BROWSER_CLOSE', default=False)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/'
# Celery / broker configuration
# Supports RabbitMQ (AMQP) via `CELERY_BROKER_URL` environment variable.
# Default is local RabbitMQ (guest/guest) for development. In production
# set `CELERY_BROKER_URL` to e.g. amqp://user:pass@rabbitmq:5672//
CELERY_BROKER_URL = env.str('CELERY_BROKER_URL', default=None)
CELERY_BROKER_AVAILABLE = CELERY_BROKER_URL is not None

# Result backend defaults to Redis (existing `REDIS_URL`). If you prefer
# use RabbitMQ RPC backend set `CELERY_RESULT_BACKEND` accordingly.
CELERY_RESULT_BACKEND = REDIS_URL if REDIS_AVAILABLE else None

# Recommended Celery serialization settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Production security settings (read from env)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=env.bool('DEBUG', False) is False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not env.bool('DEBUG', False))
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not env.bool('DEBUG', False))
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)

# Logging: simple console logger suitable for container/Heroku-like environments
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(levelname)s] %(asctime)s %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'root': {
        'handlers': ['console'],
        'level': env.str('LOG_LEVEL', default='INFO'),
    },
}


