# Generated by Codex on 2026-04-26

from django.db import migrations


def _rename_table_if_needed(schema_editor, old_name: str, new_name: str) -> None:
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if old_name in existing_tables and new_name not in existing_tables:
        schema_editor.execute(
            f'ALTER TABLE "{old_name}" RENAME TO "{new_name}";'
        )


def forwards(apps, schema_editor):
    _rename_table_if_needed(schema_editor, "movies_movie_actor", "movies_movie_actors")
    _rename_table_if_needed(schema_editor, "movies_movie_category", "movies_movie_categories")
    _rename_table_if_needed(schema_editor, "movies_movie_director", "movies_movie_directors")
    _rename_table_if_needed(schema_editor, "movies_movie_subcategory", "movies_movie_subcategories")


def backwards(apps, schema_editor):
    _rename_table_if_needed(schema_editor, "movies_movie_actors", "movies_movie_actor")
    _rename_table_if_needed(schema_editor, "movies_movie_categories", "movies_movie_category")
    _rename_table_if_needed(schema_editor, "movies_movie_directors", "movies_movie_director")
    _rename_table_if_needed(schema_editor, "movies_movie_subcategories", "movies_movie_subcategory")


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0056_movie_homiy_movie_yoshcheklovi"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

