# Generated by Django 6.0 on 2026-04-26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0057_rename_m2m_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=True, populate_from="name"),
        ),
    ]

